### PR TITLE
support laravel 9

### PR DESCRIPTION
**Pull request by atmonshi**
add support for laravel 9

### CODE REVIEW

**Comment by vedmant** [comment]
Thanks, I can merge and make a release tomorrow, it also needs Travis file updated to run tests with Laravel 9

**Comment by atmonshi** [comment]
you are welcome :)
I forget about Travis. I made another push.

**Comment by atmonshi** [comment]
OK, it was failing with:

```
Test directory "/home/travis/build/atmonshi/laravel-feed-reader/./tests/Feature" not found
The command "vendor/bin/phpunit" exited with 2.
```

so I had to edit the `phpunit.xml` file.
but now it's trying to install laravel 5 with PHP 8!
I don't know how to work around this.
https://app.travis-ci.com/github/atmonshi/laravel-feed-reader/jobs/558894571

**Comment by vedmant** [comment]
There are env variables in Travis file that describe what versions run with what, I can check that tomorrow, from phone today.

**Comment by bashgeek** [comment]
Oh, great to see this already in the works, was running into this issue today :-)

**Comment by vedmant** [comment]
Actually looks like Travis is not available anymore, I'll migrate to github actions later, for now I merged and published a release.

**Pull request merged**
